# Generated by Django 5.1.2 on 2025-01-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('self_delivery_of_mail', 'Відділення'), ('post_office', 'Поштомат'), ('courier', "Кур'єр")], default='post_office', max_length=30, verbose_name='Тип доставки'),
        ),
    ]
