# Generated by Django 5.1.2 on 2025-01-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_delivery_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(choices=[('branch', 'Відділення'), ('parcel_locker', 'Поштомат'), ('courier', "Кур'єр")], default='parcel_locker', max_length=30, verbose_name='Тип доставки'),
        ),
    ]
