# Generated by Django 5.1.2 on 2025-01-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_delivery_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('PAID', 'Оплачено'), ('NOT_PAID', 'Не оплачено'), ('CASH_ON_DELIVERY', 'Оплата при отриманні')], default='NOT_PAID', max_length=20, verbose_name='Статус оплати'),
        ),
    ]
