# Generated by Django 5.1.2 on 2024-12-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos/products/%Y/%m/%d/', verbose_name='Зображення'),
        ),
    ]
