# Generated by Django 5.1.2 on 2024-12-04 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['-created_at'], 'verbose_name': 'Кошик', 'verbose_name_plural': 'Кошик'},
        ),
    ]
